#!/bin/bash

# create $HOME/local stuffs if needed
if [ -d $HOME/.dotsplat ]; then
 	echo ""
else
	mkdir $HOME/.dotsplat
fi

INSTALLHELPER=$HOME/.dotsplat/.install.helper
# grabbing latest version of install.helper and sourcing it
curl -fsSL http://install.hovr2pi.org/install.helper > $INSTALLHELPER
source $INSTALLHELPER

checkgit

git clone git://github.com/hovr2pi/dotsplat.git $HOME/.dotsplat.git

bootstrapbash
