#!/bin/bash


INSTALLHELPER=$HOME/.scibrew/install.helper
# grabbing latest version of install.helper and sourcing it
curl -fsSL http://install.hovr2pi.org/install.helper > $INSTALLHELPER
source $HOME/.scibrew/install.helper

checkgit

git clone git://github.com/hovr2pi/dotsplat.git $HOME/.dotsplat.git

callsetup

