#!/bin/bash

echo ""
echo "Run the following commands:"
echo "git clone git://github.com/andsens/homeshick.git $HOME/.homesick/repos/homeshick"
echo "printf '\nsource "$HOME/.homesick/repos/homeshick/homeshick.sh"' >> $HOME/.bashrc"
echo "source $HOME/.bashrc"
echo "$HOME/.homesick/repos/homeshick//bin/homeshick link dotfiles"
echo ""

