#!/bin/bash
INSTALLHELPER=$HOME/.scibrew/install.helper

#shell script download the install script

# grabbing install.helper ...
wget http://install.hovr2pi.org/install.helper 
chmod +x ./install.helper
mv install.helper $INSTALLHELPER

if [ -f $INSTALLHELPER ]; then
	.   $INSTALLHELPER
else
	echo "$INSTALLHELPER not found!"
	exit 1
fi


checkwgetarx
checkbar
checkbrew
checkmakedepend


wgetarx http://install.hovr2pi.org/contrib/molden.tar.gz
bar -n $INSTALLDIR/molden.tar.gz | tar xzpf - && cd molden5.0
make

