#!/bin/bash
INSTALLHELPER=/tmp/install.helper.$$

# grabbing latest version of install.helper and sourcing it
curl -fsSL http://install.hovr2pi.org/install.helper > $INSTALLHELPER

source $INSTALLHELPER
chmod +x ./install.helper


checkwgetarx
checkbar
checkbrew
checkmakedepend


wgetarx http://install.hovr2pi.org/contrib/molden.tar.gz
cd molden5.0
make

