#!/bin/bash
INSTALLDIR=`pwd`
INSTALLHELPER=/tmp/install.helper.$USER

#shell script download the install script

# grabbing install.helper ...
curl -l http://install.hovr2pi.org/install.helper >> install.helper
chmod +x ./install.helper
mv install.helper $INSTALLHELPER

if [ -f $INSTALLHELPER ]; then
	.   $INSTALLHELPER
else
	echo "$INSTALLHELPER not found!"
	exit 1
fi


checkwgetarx
checkbar
checkbrew
checkmakedepend


curl -l http://install.hovr2pi.org/bin/scibrew.sh > $HOME/local/bin/scibrew
chmod +x $HOME/local/bin/scibrew
scibrew -t
scibrew -m
rm /tmp/install.helper.$USER
