#!/bin/bash
INSTALLDIR=`pwd`
INSTALLHELPER=/tmp/install.helper.$$

#shell script download the install script

# grabbing install.helper ...
wget http://install.hovr2pi.org/install.helper 
chmod +x ./install.helper
mv install.helper $INSTALLHELPER

if [ -f $INSTALLHELPER ]; then
	.   $INSTALLHELPER
else
	echo "$INSTALLHELPER not found!"
	exit 1
fi


checkwgetarx
checkbar
checkbrew
checkmakedepend


curl -l http://install.hovr2pi.org/bin/scibrew > $HOME/local/bin/scibrew
rm /tmp/install.helper.$$
