#!/bin/bash

if [ -d $HOME/.scibrew ]; then
	echo "~/.scibrew already exists"
else
	mkdir $HOME/.scibrew
fi

#shell script download the install script

# grabbing install.helper if needed ...
if [ -f $HOME/.scibrew/install.help ]; then
	echo "install.helper found!"
else
	echo "installing install.helper ..."
	curl -l http://install.hovr2pi.org/install.helper > $HOME/.scibrew/install.helper
	chmod +x $HOME/.scibrew/install.helper
fi

source $HOME/.scibrew/install.helper

checkwgetarx
checkbar
checkbrew
checkmakedepend


curl -l http://install.hovr2pi.org/bin/scibrew.sh > $HOME/local/bin/scibrew
chmod +x $HOME/local/bin/scibrew
brew doctor
scibrew -t
scibrew -m
